

---

In [ ]:
import os
import pandas as pd

In [ ]:
!git clone https://github.com/farelarden/Dicoding-Capstone-ML.git

Cloning into 'Dicoding-Capstone-ML'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 132 (delta 44), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (132/132), 867.29 KiB | 3.69 MiB/s, done.
Resolving deltas: 100% (44/44), done.

In [ ]:
df1 = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Clean Dataset/02 - Makanan.csv')
df2 = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Clean Dataset/02 - Minuman.csv')
df3 = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Clean Dataset/03 - Sewa Rumah.csv')
df4 = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Clean Dataset/04 - Sandang.csv')
df5 = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Clean Dataset/07 - Transportasi.csv')

In [ ]:
df1.head()

    BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0  Jan-14           1.10             0.25  ...         2.26     1.89           0.76
1  Feb-14           0.88             0.00  ...         0.80     0.26           0.38
2  Mar-14           1.42             0.10  ...         0.00     0.24           0.39
3  Apr-14           0.17             0.04  ...         0.00     0.81           0.41
4  May-14          -0.01             0.00  ...         0.00     0.07           0.27

[5 rows x 83 columns]

In [ ]:
df1.BULAN = df2.BULAN.str.replace("-", " ")

In [ ]:
df1.BULAN = pd.to_datetime(df1.BULAN, format="%b %y")

In [ ]:
df1.head()

       BULAN  KOTA MEULABOH  ...  MERAUKE  KOTA JAYAPURA
0 2014-01-01           1.10  ...     1.89           0.76
1 2014-02-01           0.88  ...     0.26           0.38
2 2014-03-01           1.42  ...     0.24           0.39
3 2014-04-01           0.17  ...     0.81           0.41
4 2014-05-01          -0.01  ...     0.07           0.27

[5 rows x 83 columns]

In [ ]:
month_vals = []
for i in range(df1.shape[0]):
    month_vals.append(i)

df1['URUTAN'] = month_vals

In [ ]:
df1.tail()

        BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  MERAUKE  KOTA JAYAPURA  URUTAN
89 2021-06-01          -0.68            -0.97  ...     1.00          -1.00      89
90 2021-07-01           0.80            -1.17  ...    -1.13          -0.19      90
91 2021-08-01          -0.44             1.37  ...    -3.39          -1.15      91
92 2021-09-01          -2.56            -1.71  ...    -3.56          -1.58      92
93 2021-10-01           2.06             1.39  ...     0.21          -0.58      93

[5 rows x 84 columns]

In [ ]:
cols_at_start = ['URUTAN']
df1 = df1[[c for c in cols_at_start if c in df1]+[c for c in df1 if c not in cols_at_start] 
        ]

In [ ]:
df1.head()

   URUTAN      BULAN  KOTA MEULABOH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0       0 2014-01-01           1.10  ...         2.26     1.89           0.76
1       1 2014-02-01           0.88  ...         0.80     0.26           0.38
2       2 2014-03-01           1.42  ...         0.00     0.24           0.39
3       3 2014-04-01           0.17  ...         0.00     0.81           0.41
4       4 2014-05-01          -0.01  ...         0.00     0.07           0.27

[5 rows x 84 columns]



---

In [ ]:
df2.head()

    BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0  Jan-14           0.59            -0.31  ...         3.13    -0.45           0.47
1  Feb-14           0.12             0.22  ...         2.64     2.59           0.32
2  Mar-14           0.14             0.57  ...         0.00    -0.24           0.01
3  Apr-14           0.01            -0.06  ...        -0.10     0.27           0.27
4  May-14           0.32             0.00  ...        -0.35     0.12           0.23

[5 rows x 83 columns]

In [ ]:
df2.BULAN = df2.BULAN.str.replace("-", " ")

In [ ]:
df2.BULAN = pd.to_datetime(df2.BULAN, format="%b %y")

In [ ]:
df2.head()

       BULAN  KOTA MEULABOH  ...  MERAUKE  KOTA JAYAPURA
0 2014-01-01           0.59  ...    -0.45           0.47
1 2014-02-01           0.12  ...     2.59           0.32
2 2014-03-01           0.14  ...    -0.24           0.01
3 2014-04-01           0.01  ...     0.27           0.27
4 2014-05-01           0.32  ...     0.12           0.23

[5 rows x 83 columns]

In [ ]:
# month_vals = []
# for i in range(df1.shape[0]):
#     month_vals.append(i)

df2['URUTAN'] = month_vals

In [ ]:
df2.tail()

        BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  MERAUKE  KOTA JAYAPURA  URUTAN
89 2021-06-01           0.27             0.01  ...     0.02           2.48      89
90 2021-07-01           0.00             0.17  ...     0.32           0.45      90
91 2021-08-01           0.13             0.00  ...    -2.32          -0.13      91
92 2021-09-01          -0.13             0.04  ...     0.13           0.08      92
93 2021-10-01          -0.16            -0.07  ...     0.09          -0.18      93

[5 rows x 84 columns]

In [ ]:
# cols_at_start = ['URUTAN']
df2 = df2[[c for c in cols_at_start if c in df2]+[c for c in df2 if c not in cols_at_start] 
        ]

In [ ]:
df2.head()

   URUTAN      BULAN  KOTA MEULABOH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0       0 2014-01-01           0.59  ...         3.13    -0.45           0.47
1       1 2014-02-01           0.12  ...         2.64     2.59           0.32
2       2 2014-03-01           0.14  ...         0.00    -0.24           0.01
3       3 2014-04-01           0.01  ...        -0.10     0.27           0.27
4       4 2014-05-01           0.32  ...        -0.35     0.12           0.23

[5 rows x 84 columns]



---

In [ ]:
df3.head()

    BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0  Jan-14           1.67             1.54  ...         0.29     1.11           0.40
1  Feb-14          -0.52            -0.05  ...         0.97    -0.05           0.39
2  Mar-14          -0.01             0.25  ...         1.35     0.39           0.16
3  Apr-14           0.06             0.13  ...         0.05     0.07           0.25
4  May-14           0.11             0.20  ...        -0.02     0.03           0.26

[5 rows x 83 columns]

In [ ]:
df3.BULAN = df4.BULAN.str.replace("-", " ")

In [ ]:
df3.BULAN = pd.to_datetime(df3.BULAN, format="%b %y")

In [ ]:
df3.head()

       BULAN  KOTA MEULABOH  ...  MERAUKE  KOTA JAYAPURA
0 2014-01-01           1.67  ...     1.11           0.40
1 2014-02-01          -0.52  ...    -0.05           0.39
2 2014-03-01          -0.01  ...     0.39           0.16
3 2014-04-01           0.06  ...     0.07           0.25
4 2014-05-01           0.11  ...     0.03           0.26

[5 rows x 83 columns]

In [ ]:
# month_vals = []
# for i in range(df1.shape[0]):
#     month_vals.append(i)

df3['URUTAN'] = month_vals

In [ ]:
df3.tail()

        BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  MERAUKE  KOTA JAYAPURA  URUTAN
89 2021-06-01            0.0             0.00  ...      0.0           0.53      89
90 2021-07-01            0.0             0.00  ...      0.0           0.25      90
91 2021-08-01            0.0             0.05  ...      0.0           0.00      91
92 2021-09-01            0.0             0.98  ...      0.0           0.00      92
93 2021-10-01            0.0             0.00  ...      0.0           0.00      93

[5 rows x 84 columns]

In [ ]:
# cols_at_start = ['URUTAN']
df3 = df3[[c for c in cols_at_start if c in df3]+[c for c in df3 if c not in cols_at_start] 
        ]

In [ ]:
df3.head()

   URUTAN      BULAN  KOTA MEULABOH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0       0 2014-01-01           1.67  ...         0.29     1.11           0.40
1       1 2014-02-01          -0.52  ...         0.97    -0.05           0.39
2       2 2014-03-01          -0.01  ...         1.35     0.39           0.16
3       3 2014-04-01           0.06  ...         0.05     0.07           0.25
4       4 2014-05-01           0.11  ...        -0.02     0.03           0.26

[5 rows x 84 columns]



---

In [ ]:
df4.head()

    BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0  Jan-14           2.07             0.80  ...         0.63    -0.16           0.55
1  Feb-14           1.10             0.44  ...         0.00     0.43           0.57
2  Mar-14          -0.08             0.41  ...         0.00     0.44           0.08
3  Apr-14           0.55            -0.41  ...         0.00    -0.59          -0.25
4  May-14           2.62             0.15  ...         0.00     0.33           0.12

[5 rows x 83 columns]

In [ ]:
df4.BULAN = df5.BULAN.str.replace("-", " ")

In [ ]:
df4.BULAN = pd.to_datetime(df4.BULAN, format="%b %y")

In [ ]:
df4.head()

       BULAN  KOTA MEULABOH  ...  MERAUKE  KOTA JAYAPURA
0 2014-01-01           2.07  ...    -0.16           0.55
1 2014-02-01           1.10  ...     0.43           0.57
2 2014-03-01          -0.08  ...     0.44           0.08
3 2014-04-01           0.55  ...    -0.59          -0.25
4 2014-05-01           2.62  ...     0.33           0.12

[5 rows x 83 columns]

In [ ]:
# month_vals = []
# for i in range(df1.shape[0]):
#     month_vals.append(i)

df4['URUTAN'] = month_vals

In [ ]:
df4.tail()

        BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  MERAUKE  KOTA JAYAPURA  URUTAN
89 2021-06-01           0.15             0.23  ...     0.12          -0.02      89
90 2021-07-01          -0.22             0.61  ...    -0.05           0.36      90
91 2021-08-01           0.00            -0.24  ...     0.01           0.09      91
92 2021-09-01           0.21             0.08  ...    -0.16           0.00      92
93 2021-10-01          -0.30            -0.04  ...     0.00           0.06      93

[5 rows x 84 columns]

In [ ]:
# cols_at_start = ['URUTAN']
df4 = df4[[c for c in cols_at_start if c in df4]+[c for c in df4 if c not in cols_at_start] 
        ]

In [ ]:
df4.head()

   URUTAN      BULAN  KOTA MEULABOH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0       0 2014-01-01           2.07  ...         0.63    -0.16           0.55
1       1 2014-02-01           1.10  ...         0.00     0.43           0.57
2       2 2014-03-01          -0.08  ...         0.00     0.44           0.08
3       3 2014-04-01           0.55  ...         0.00    -0.59          -0.25
4       4 2014-05-01           2.62  ...         0.00     0.33           0.12

[5 rows x 84 columns]



---

In [ ]:
df5.head()

    BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0  Jan-14           0.50             0.95  ...         0.00    -2.15           0.27
1  Feb-14           0.39             0.06  ...        -7.48     0.00           0.23
2  Mar-14           0.00             0.13  ...         4.90     1.47           0.33
3  Apr-14           0.00             1.42  ...        -2.17     0.08           0.29
4  May-14           0.01            -0.01  ...         2.50     0.00           0.31

[5 rows x 83 columns]

In [ ]:
df5.BULAN = df5.BULAN.str.replace("-", " ")

In [ ]:
df5.BULAN = pd.to_datetime(df5.BULAN, format="%b %y")

In [ ]:
df5.head()

       BULAN  KOTA MEULABOH  ...  MERAUKE  KOTA JAYAPURA
0 2014-01-01           0.50  ...    -2.15           0.27
1 2014-02-01           0.39  ...     0.00           0.23
2 2014-03-01           0.00  ...     1.47           0.33
3 2014-04-01           0.00  ...     0.08           0.29
4 2014-05-01           0.01  ...     0.00           0.31

[5 rows x 83 columns]

In [ ]:
# month_vals = []
# for i in range(df1.shape[0]):
#     month_vals.append(i)

df5['URUTAN'] = month_vals

In [ ]:
df5.tail()

        BULAN  KOTA MEULABOH  KOTA BANDA ACEH  ...  MERAUKE  KOTA JAYAPURA  URUTAN
89 2021-06-01          -0.23             1.40  ...    -2.31          -6.18      89
90 2021-07-01          -0.21             1.52  ...    -0.72          -5.53      90
91 2021-08-01          -0.18             1.52  ...    -0.80          -6.19      91
92 2021-09-01          -0.13             2.30  ...     0.11          -5.93      92
93 2021-10-01          -0.11             2.84  ...     1.58          -0.95      93

[5 rows x 84 columns]

In [ ]:
# cols_at_start = ['URUTAN']
df5 = df5[[c for c in cols_at_start if c in df5]+[c for c in df5 if c not in cols_at_start] 
        ]

In [ ]:
df5.head()

   URUTAN      BULAN  KOTA MEULABOH  ...  KOTA SORONG  MERAUKE  KOTA JAYAPURA
0       0 2014-01-01           0.50  ...         0.00    -2.15           0.27
1       1 2014-02-01           0.39  ...        -7.48     0.00           0.23
2       2 2014-03-01           0.00  ...         4.90     1.47           0.33
3       3 2014-04-01           0.00  ...        -2.17     0.08           0.29
4       4 2014-05-01           0.01  ...         2.50     0.00           0.31

[5 rows x 84 columns]

In [ ]:
from google.colab import files
df1.to_csv('fix 02 - Makanan.csv')
files.download('fix 02 - Makanan.csv')

In [ ]:
df2.to_csv('fix 02 - Minuman.csv')
files.download('fix 02 - Minuman.csv')

In [ ]:
df3.to_csv('fix 03 - Rumah.csv')
files.download('fix 03 - Rumah.csv')

In [ ]:
df4.to_csv('fix 04 - Sandang.csv')
files.download('fix 04 - Sandang.csv')

In [ ]:
df5.to_csv('fix 07 - Transportasi.csv')
files.download('fix 07 - Transportasi.csv')